# Generated by Django 5.0.3 on 2024-04-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
